import Head from "next/head";
import { FaWhatsapp, FaInstagram,FaEnvelope} from 'react-icons/fa';
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";

// import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import Image from "next/image";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import port from "../public/porta.png"

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Ecualandia</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resumen
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Juan Leopoldo
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Programador y editor(videos y fotos).
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Hola, soy Leo desarollador Frontend y editor de videos, autodidacta, me gusta aprender y entre mis habilidades y pasatiempos tengo:
              jugar al balonces, editar fotos com gimp, aprender de neuromarketing y marketing digital, 
              y como no crear paginas web obtimizadas para el CEO (como esta en la que estas)
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="mailto:obamajuan20@gmail.com"> <FaEnvelope/> </a>
              <a href="https://wa.me/message/TYC2ZS6S4JRGI1  "> <FaWhatsapp/></a>
              <a href="https://www.instagram.com/invites/contact/?i=m3t1aye6yshw&utm_content=u5fifhq"> <FaInstagram/> </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-900  w-100 h-96 relative overflow-hidden m-8 mt-20 md:h-96 md:w-96">
              <Image src={port} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Ofertas  & servicios</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Actualmente soy freelance (no trabajo para una empresa fija), realicé un trabajo para
              <span className="text-teal-500"> agencias </span>
              consultorias de <span className="text-teal-500">startups</span>
              y colaborado para algunos personas talentosas para hacer realidad sus diseños
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Ofrezco servicios de programacion y edición de videos e diseño de images
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Diseños minimalistas
              </h3>
              <p className="py-2">
                crear diseños elegantes para tu negocio
              </p>
              <h4 className="py-4 text-teal-600">Herramientas de diseño:</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Canva</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Codeo tu proyecto soñado
              </h3>
              <p className="py-2">
                Tienes una idea para tu proxima web ?, pues dejame hacerla realidad
              </p>
              <h4 className="py-4 text-teal-600">Lenguajes y herramientas:</h4>
              <p className="text-gray-800 py-1">Javascript</p>
              <p className="text-gray-800 py-1">Python</p>
              <p className="text-gray-800 py-1">Git & githup</p>
              <p className="text-gray-800 py-1">React</p>
              <p className="text-gray-800 py-1">Boostrap</p>
              <p className="text-gray-800 py-1">Sass</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Actualmente soy freelance (no trabajo para una empresa fija), realicé un trabajo para
              <span className="text-teal-500"> agencias </span>
              consultorias de <span className="text-teal-500">startups</span>
              y colaborado para algunos personas talentosas para hacer realidad sus diseños
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
